add handler for game start
DeNeMiX83/black_jack pull request #3
Opened 2023-03-02 16:55 UTC by DeNeMiX83

добавил обработчик, который при старте игры, в БД создает игру и игроков

2023-03-02 21:43 UTC, ivaaahn requested changes

2023-03-02 21:43 UTC, ivaaahn commented on app/core/game/handlers/start_game.py
> +        await self._add_players_to_game(game.players, self.game)
что насчет транзакций?

2023-03-02 21:43 UTC, ivaaahn commented
за протоколы лайк

2023-03-02 22:28 UTC, DeNeMiX83 commented on app/core/game/handlers/start_game.py
> +        await self._add_players_to_game(game.players, self.game)
так тут транзакции)
как видно коммит только в самом конце делается)

2023-03-02 22:28 UTC, DeNeMiX83 commented on app/core/game/handlers/start_game.py
> +        await self._add_players_to_game(game.players, self.game)
реализация gateway еще не сделана
ибо ждал разрешения на слияния с коммитами для алхимии

2023-03-02 22:29 UTC, DeNeMiX83 commented on app/core/game/handlers/start_game.py
> +        await self._add_players_to_game(game.players, self.game)
в реализации будет session.add(object)
вызов коммита там не будет, для этого как раз и создан commiter

2023-03-03 12:05 UTC, ivaaahn approved these changes

2023-03-03 15:40 UTC, merged