add handler cteate_game via tg
DeNeMiX83/black_jack pull request #9
Opened 2023-03-08 09:15 UTC by DeNeMiX83

2023-03-09 20:46 UTC, ivaaahn commented on app/presentation/tg_bot/build_di.py
> +def build(container: Container) -> None:
работает в итоге?

2023-03-09 20:46 UTC, ivaaahn commented on app/presentation/tg_bot/headers/add_player.py
> +        chat_id=update.callback_query.message.chat.id  # type: ignore
а на что ругается-то?

2023-03-09 20:46 UTC, ivaaahn commented on app/presentation/tg_bot/headers/create_game.py
> +        await asyncio.sleep(delta)
Тестил на двух чатах параллельно?

2023-03-09 20:59 UTC, DeNeMiX83 commented on app/presentation/tg_bot/build_di.py
> +def build(container: Container) -> None:
ну типо)

2023-03-09 21:00 UTC, DeNeMiX83 commented on app/presentation/tg_bot/headers/add_player.py
> +        chat_id=update.callback_query.message.chat.id  # type: ignore
ну там стоят Optional думает что пусто там

2023-03-09 21:00 UTC, DeNeMiX83 commented on app/presentation/tg_bot/headers/create_game.py
> +        await asyncio.sleep(delta)
еще нет, надо до ума довести, состояния ща пытаюсь прикрутить, и фильры для них

2023-03-10 20:31 UTC, ivaaahn commented on app/presentation/tg_bot/headers/add_player.py
> +        chat_id=update.callback_query.message.chat.id  # type: ignore
можно делать typing.cast

2023-03-10 20:31 UTC, ivaaahn commented on app/presentation/tg_bot/headers/create_game.py
> +        await asyncio.sleep(delta)
Подозрение,что не будет работать (

2023-03-10 23:08 UTC, DeNeMiX83 commented on app/presentation/tg_bot/headers/create_game.py
> +        await asyncio.sleep(delta)
хм, печально, ну пока не вижу, что тут это выдает)

2023-03-11 14:09 UTC, DeNeMiX83 commented on app/presentation/tg_bot/headers/create_game.py
> +        await asyncio.sleep(delta)
есть мысли, сделаю

2023-03-12 10:00 UTC, ivaaahn requested changes

2023-03-12 10:00 UTC, ivaaahn commented on app/presentation/tg_bot/headers/motion.py
> +async def motion_transfer_stroke(update: Update, bot: TgBot):
тоже супербольшая функция, декомпозировать бы. Сложно читать и воспринимать

2023-03-12 10:00 UTC, ivaaahn commented on app/presentation/tg_bot/states.py
> +class GameStates(Enum):
str, Enum комфортнее обычно. Не требует везде ставить .value

2023-03-12 11:40 UTC, DeNeMiX83 commented on app/core/game/entities/player.py
>      PLAYING = 1
не очень понял)

2023-03-12 11:40 UTC, DeNeMiX83 commented on app/core/game/handlers/get_card.py
> +        cards = [
понял

2023-03-12 11:41 UTC, DeNeMiX83 commented on app/core/game/handlers/get_card.py
> +        player = await self._player_gateway.get(player_id)
не понял

2023-03-13 19:46 UTC, merged